#!/usr/bin/env bash

name=$1

if [ -z $name ]
then
    name="screenshot_$(date +"%d_%H:%M:%S")"
else
    name="$name"
fi

cd
xwd -root -out "$name"
ffmpeg -i $name "$name.png"
rm "$name"
mv "$name.png" ~/screenshots
